//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch TrayMenu.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDS_ABOUTBOX                    101
#define IDD_TRAYMENU_DIALOG             102
#define IDI_ICON_MIXED                  128
#define IDI_ICON_BLUE                   129
#define IDR_MENU_RIGHT                  130
#define IDI_ICON_BLACK                  131
#define IDI_ICON_GREEN                  132
#define IDI_ICON_GREY                   133
#define IDI_ICON_ORANGE                 134
#define IDI_ICON_PINK                   135
#define IDI_ICON_RED                    136
#define IDI_ICON_VIOLET                 137
#define IDI_ICON_WHITE                  138
#define IDI_ICON_YELLOW                 139
#define IDI_ICON_LIME                   140
#define IDI_ICON_FOLDER                 141
#define IDI_ICON_FILE                   142
#define IDI_ICON_ABOUT                  143
#define IDI_ICON_CLOSE                  144
#define IDI_ICON_EXIT                   145
#define IDI_ICON_EXPLORER               146
#define IDI_ICON_RELOAD                 147
#define IDI_ICON_SETTINGS               148
#define IDI_ICON_WEBSITE                149
#define IDI_ICON_SETTINGS_ICON          150
#define IDI_ICON_SETTINGS_LOC           151
#define IDI_ICON_SETTINGS_FOLDF         152
#define IDI_ICON_SELECT_FOLDER          153
#define IDI_ICON_AUTOSTART              154
#define IDI_ICON_ADD_FOLDER             155
#define IDI_ICON_REM_FOLDER             156
#define IDI_ICON_BROWSE_FOLDER          157
#define IDI_ICON_CREATE_LNK             158
#define IDI_ICON_CLICK                  159
#define IDI_ICON_COLORS                 160
#define IDI_ICON_COLORS_DEF             161
#define IDI_ICON_COLORS_LIG             162
#define IDI_ICON_COLORS_DRK             163
#define IDI_ICON_COLORS_OWN             164
#define IDI_ICON_COLORS_CUST            165
#define IDI_ICON_INCLUDE                166
#define IDI_ICON_HOTKEY                 167
#define IDI_ICON_LEFTMOST               168
#define IDI_ICON_EXP_SETTINGS           169
#define IDI_ICON_SAVE                   170
#define IDI_ICON_DELETE                 171
#define IDI_ICON_RESTORE                172
#define IDC_HOTKEY                      1000
#define IDC_STATIC_MESSAGE              1001
#define IDC_EDIT                        1002
#define ID_SETTINGS                     32781
#define ID_EXIT                         32782
#define ID_RELOAD                       32783
#define ID_SETTINGS_ICON                32784
#define ID_ICON_BLUE                    32785
#define ID_ICON_GREEN                   32786
#define ID_ICON_LIME                    32787
#define ID_ICON_YELLOW                  32788
#define ID_ICON_ORANGE                  32789
#define ID_ICON_PINK                    32790
#define ID_ICON_BLACK                   32791
#define ID_ICON_GREY                    32792
#define ID_ICON_VIOLET                  32793
#define ID_ICON_WHITE                   32794
#define ID_ICON_RED                     32795
#define ID_ICON_MULTICOLOR              32796
#define ID_SETTINGS_LOCALIZE            32797
#define ID_SETTINGS_FOLDF               32798
#define ID_SELECT_FOLDER                32799
#define ID_AUTOSTART                    32800
#define ID_ADD_FOLDER                   32801
#define ID_REM_FOLDER                   32802
#define ID_REM_FOLDER_MAX               32902
#define ID_ABOUT                        32903
#define ID_ABOUT_TITLE                  32904
#define ID_ABOUT_VERSION                32905
#define ID_ABOUT_WEBSITE                32906
#define ID_OPEN_FOLDER                  32907
#define ID_CLOSE                        32908
#define ID_CREATE_SHORTCUT              32909
#define ID_BROWSE_FOLDER                32910
#define ID_SEL_FOLDER                   32911
#define ID_SEL_FOLDER_MAX               32930
#define ID_SETTINGS_CLICK               32931
#define ID_SETTINGS_COLORS              32932
#define ID_COLORS                       32933
#define ID_COLORS_MAX                   33032
#define ID_SETTINGS_COLORS_CUST         33033
#define ID_COLORS_CUST_TXT              33034
#define ID_COLORS_CUST_BGD              33035
#define ID_COLORS_CUST_SEP              33036
#define ID_COLORS_CUST_ITX              33037
#define ID_COLORS_CUST_IOB              33038
#define ID_COLORS_CUST_IIB              33039
#define ID_COLORS_CUST_IBG              33040
#define ID_INCLUDE_FOLDER               33041
#define ID_INC_DESKTOP                  33042
#define ID_INC_STARTMENU                33043
#define ID_DEFINE_HOTKEY                33044
#define ID_SETTINGS_LEFTMOST            33045
#define ID_EXPORT_SETTINGS              33046
#define ID_ICON_FOLDER_SELECTED         33047
#define ID_SHELL_MENU                   33048
#define ID_SHELL_MENU_MAX               33057
#define ID_COLORS_SAVE                  33058
#define ID_COLORS_DELETE                33059
#define ID_COLORS_RESTORE               33060
#define ID_MENU_START                   33061

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        173
#define _APS_NEXT_COMMAND_VALUE         33062
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
